//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIES_WORK_CATEGORY
    {
        public int OBJECTID { get; set; }
        public Nullable<int> WORK_CATEGORY_ID { get; set; }
        public Nullable<int> CATEGORIES_ID { get; set; }
    
        public virtual CATEGORy CATEGORy { get; set; }
        public virtual WORKS_CATEGORY WORKS_CATEGORY { get; set; }
    }
}
