//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CROP_SORT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CROP_SORT()
        {
            this.PLANNINGPLANs = new HashSet<PLANNINGPLAN>();
            this.PLANNINGPLANDETAILS = new HashSet<PLANNINGPLANDETAIL>();
            this.MYSILOSTOCKs = new HashSet<MYSILOSTOCK>();
            this.MYSILOSTOCKDETAILS = new HashSet<MYSILOSTOCKDETAIL>();
        }
    
        public int OBJECTID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> CROP_ID { get; set; }
    
        public virtual CROP CROP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANNINGPLAN> PLANNINGPLANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANNINGPLANDETAIL> PLANNINGPLANDETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MYSILOSTOCK> MYSILOSTOCKs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MYSILOSTOCKDETAIL> MYSILOSTOCKDETAILS { get; set; }
    }
}
