//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRENT_ACCOUNT
    {
        public int OBJECTID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<decimal> CURRENT_BANK_CASH { get; set; }
        public Nullable<decimal> MAIN_CASH { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> HAND_CASH { get; set; }
        public Nullable<decimal> WAITING_CASH { get; set; }
    }
}
