//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCMESSAGE
    {
        public int OBJECTID { get; set; }
        public Nullable<int> SENDERID { get; set; }
        public Nullable<int> RECIVED { get; set; }
        public string TITLE { get; set; }
        public Nullable<int> DOCID { get; set; }
        public Nullable<int> OPRTYPE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string Note { get; set; }
    
        public virtual DOCUMENT DOCUMENT { get; set; }
        public virtual Worker Worker { get; set; }
        public virtual Worker Worker1 { get; set; }
    }
}
