//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FERTILIZER_STOCK
    {
        public int OBJECTID { get; set; }
        public Nullable<int> FERTILIZER_ID { get; set; }
        public Nullable<decimal> UNIT { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> USED_DATE { get; set; }
    
        public virtual FERTILIZER FERTILIZER { get; set; }
    }
}
