//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FERTILIZER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FERTILIZER()
        {
            this.FERTILIZER_STOCK = new HashSet<FERTILIZER_STOCK>();
            this.FERTILIZER_WORK_PLAN = new HashSet<FERTILIZER_WORK_PLAN>();
            this.WORKPLAN2TASKFELTILIZER = new HashSet<WORKPLAN2TASKFELTILIZER>();
        }
    
        public int OBJECTID { get; set; }
        public Nullable<int> FIRM_ID { get; set; }
        public Nullable<int> MARK_ID { get; set; }
        public Nullable<int> MAIN_COMPONENT_ID { get; set; }
        public Nullable<int> PACKING_ID { get; set; }
        public Nullable<int> UNIT_TYPE_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> CATEGORY_ID { get; set; }
        public Nullable<decimal> WATER_PER_KG { get; set; }
    
        public virtual CATEGORy CATEGORy { get; set; }
        public virtual MAIN_COMPONENTS MAIN_COMPONENTS { get; set; }
        public virtual FIRM FIRM { get; set; }
        public virtual MARK MARK { get; set; }
        public virtual PACKING PACKING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FERTILIZER_STOCK> FERTILIZER_STOCK { get; set; }
        public virtual UNIT UNIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FERTILIZER_WORK_PLAN> FERTILIZER_WORK_PLAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORKPLAN2TASKFELTILIZER> WORKPLAN2TASKFELTILIZER { get; set; }
    }
}
