//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGENOTIFICATION
    {
        public int OBJECTID { get; set; }
        public int SENDERID { get; set; }
        public int RECIVERID { get; set; }
        public bool STATUS { get; set; }
        public int WORKPLANID { get; set; }
        public System.DateTime SENDEDTIME { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual WORK_PLAN WORK_PLAN { get; set; }
    }
}
