//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MYSILOSTOCK
    {
        public int OBJECTID { get; set; }
        public int MYSILOID { get; set; }
        public int CROPSORTID { get; set; }
        public int CROPREPREDUCTIONID { get; set; }
        public decimal TOTALCOUNT { get; set; }
    
        public virtual CROP_REPRODUCTION CROP_REPRODUCTION { get; set; }
        public virtual CROP_SORT CROP_SORT { get; set; }
        public virtual MYSILO MYSILO { get; set; }
    }
}
