//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARCEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARCEL()
        {
            this.WORK_PLAN = new HashSet<WORK_PLAN>();
            this.PLANNINGPLANs = new HashSet<PLANNINGPLAN>();
            this.WORKPLAN2PARCELS = new HashSet<WORKPLAN2PARCELS>();
        }
    
        public int OBJECTID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> PARCEL_CATEGORY_ID { get; set; }
        public Nullable<int> RESPONSER_ID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<decimal> AREA { get; set; }
        public Nullable<int> SORT_ID { get; set; }
        public Nullable<int> REPRODUCTION_ID { get; set; }
    
        public virtual PARCEL_CATEGORY PARCEL_CATEGORY { get; set; }
        public virtual Worker Worker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORK_PLAN> WORK_PLAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANNINGPLAN> PLANNINGPLANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORKPLAN2PARCELS> WORKPLAN2PARCELS { get; set; }
    }
}
