//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        public int OBJECTID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> ID_INOUT { get; set; }
        public Nullable<int> PAYMENT_TYPE_ID { get; set; }
        public Nullable<decimal> MAIN_PAYMENT { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> ALL_PAYMENT { get; set; }
        public string RELEASE { get; set; }
        public Nullable<decimal> REMNANT { get; set; }
        public string NOTE { get; set; }
    
        public virtual PAYMENT_INOUT PAYMENT_INOUT { get; set; }
        public virtual PAYMENT_TYPE PAYMENT_TYPE { get; set; }
    }
}
