//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANINGPLANBYDETAIL
    {
        public int OBJECTID { get; set; }
        public int PLANNINGPLANID { get; set; }
        public int PLANNINGDETAISID { get; set; }
        public int PLANNINGDETAISWORKID { get; set; }
        public decimal FINALLYPRICE { get; set; }
    
        public virtual PLANNINGPLAN PLANNINGPLAN { get; set; }
        public virtual PLANNINGPLANDETAIL PLANNINGPLANDETAIL { get; set; }
        public virtual PLANNINGPLANDETAILSWORK PLANNINGPLANDETAILSWORK { get; set; }
    }
}
