//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANNINGPLANDETAILSWORK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLANNINGPLANDETAILSWORK()
        {
            this.PLANINGPLANBYDETAILS = new HashSet<PLANINGPLANBYDETAIL>();
        }
    
        public int OBJECTID { get; set; }
        public int PLANNINGPLANDETAILSID { get; set; }
        public string MONTH { get; set; }
        public string WORKCANDO { get; set; }
        public string NEEDED { get; set; }
        public decimal PRICE { get; set; }
    
        public virtual PLANNINGPLANDETAIL PLANNINGPLANDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANINGPLANBYDETAIL> PLANINGPLANBYDETAILS { get; set; }
    }
}
