//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PVOT_S
    {
        public int OBJECTID_12 { get; set; }
        public Nullable<decimal> OBJECTID { get; set; }
        public Nullable<decimal> OBJECTID_1 { get; set; }
        public Nullable<decimal> ID { get; set; }
        public string TYPE { get; set; }
        public string R { get; set; }
        public string F { get; set; }
        public string HK { get; set; }
        public string RADIUS { get; set; }
        public string EKIN { get; set; }
        public string NOV { get; set; }
        public string EKIN2 { get; set; }
        public string NOTE { get; set; }
        public string NOTE1 { get; set; }
        public string LAST_WATER { get; set; }
        public string LAST_EXPRI { get; set; }
        public string LAST_FERTI { get; set; }
        public string LAST_CONTR { get; set; }
        public Nullable<short> EKIN_ID { get; set; }
        public Nullable<short> NOV_ID { get; set; }
        public Nullable<decimal> FERT_SUM { get; set; }
        public Nullable<decimal> FERT_SALARY { get; set; }
        public Nullable<decimal> WATER_SALARY { get; set; }
        public Nullable<decimal> SEED_SUM { get; set; }
        public Nullable<decimal> SEED_SALARY { get; set; }
        public Nullable<decimal> PILL_SUM { get; set; }
        public Nullable<decimal> PILL_SALARY { get; set; }
        public Nullable<decimal> INCOME_SUM { get; set; }
        public Nullable<decimal> INCOME_SALARY { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
        public Nullable<decimal> AREAS { get; set; }
    }
}
