//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueuePlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QueuePlan()
        {
            this.FERTILIZER_WORK_PLAN = new HashSet<FERTILIZER_WORK_PLAN>();
            this.WORK_PLAN_TECHNIQUE = new HashSet<WORK_PLAN_TECHNIQUE>();
            this.WORK_PLAN_WORKERS = new HashSet<WORK_PLAN_WORKERS>();
        }
    
        public int OBJECTID { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string note { get; set; }
        public Nullable<int> dailyPlanId { get; set; }
    
        public virtual DAYLY_WORK_PLAN DAYLY_WORK_PLAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FERTILIZER_WORK_PLAN> FERTILIZER_WORK_PLAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORK_PLAN_TECHNIQUE> WORK_PLAN_TECHNIQUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORK_PLAN_WORKERS> WORK_PLAN_WORKERS { get; set; }
    }
}
