//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCKMODIFY
    {
        public int OBJECTID { get; set; }
        public Nullable<int> STOCKITEMID { get; set; }
        public Nullable<int> STATUSID { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<int> PLACEID { get; set; }
        public Nullable<int> WORKERID { get; set; }
    
        public virtual STOCKPLACE STOCKPLACE { get; set; }
        public virtual STOCK STOCK { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
