//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STOCK()
        {
            this.STOCKMODIFies = new HashSet<STOCKMODIFY>();
        }
    
        public int OBJECTID { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public Nullable<short> TYPE { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public string SPEC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCKMODIFY> STOCKMODIFies { get; set; }
    }
}
