//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TECHNIQUE_TRAILER
    {
        public int OBJECTID { get; set; }
        public Nullable<int> WORK_PLAN_TECHNIQUE_ID { get; set; }
        public Nullable<int> TECHNIQUE_ID { get; set; }
    
        public virtual TECHNIQUE TECHNIQUE { get; set; }
        public virtual WORK_PLAN_TECHNIQUE WORK_PLAN_TECHNIQUE { get; set; }
    }
}
