//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TECHNIQUE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TECHNIQUE()
        {
            this.TECHNIQUE_TRAILER = new HashSet<TECHNIQUE_TRAILER>();
            this.WORK_PLAN_TECHNIQUE = new HashSet<WORK_PLAN_TECHNIQUE>();
            this.WOKRPLAN2TASKQUEUETECHNICAL = new HashSet<WOKRPLAN2TASKQUEUETECHNICAL>();
            this.WOKRPLAN2TASKQUEUETECHNICAL1 = new HashSet<WOKRPLAN2TASKQUEUETECHNICAL>();
        }
    
        public int OBJECTID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> TYPE_ID { get; set; }
        public Nullable<int> CONDITION_ID { get; set; }
        public Nullable<int> WORKING_TYPE_ID { get; set; }
    
        public virtual TECHNIQUE_CONDITION TECHNIQUE_CONDITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TECHNIQUE_TRAILER> TECHNIQUE_TRAILER { get; set; }
        public virtual TECHNIQUE_TYPE TECHNIQUE_TYPE { get; set; }
        public virtual TECHNIQUE_WORKING_TYPE TECHNIQUE_WORKING_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORK_PLAN_TECHNIQUE> WORK_PLAN_TECHNIQUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WOKRPLAN2TASKQUEUETECHNICAL> WOKRPLAN2TASKQUEUETECHNICAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WOKRPLAN2TASKQUEUETECHNICAL> WOKRPLAN2TASKQUEUETECHNICAL1 { get; set; }
    }
}
