//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.WORK_PLAN_MODIFY = new HashSet<WORK_PLAN_MODIFY>();
            this.MESSAGENOTIFICATIONs = new HashSet<MESSAGENOTIFICATION>();
            this.MESSAGENOTIFICATIONs1 = new HashSet<MESSAGENOTIFICATION>();
        }
    
        public int ID { get; set; }
        public Nullable<int> WorkerID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UserAdmin_ID { get; set; }
    
        public virtual GROUP GROUP { get; set; }
        public virtual USERADMINSTATU USERADMINSTATU { get; set; }
        public virtual Worker Worker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORK_PLAN_MODIFY> WORK_PLAN_MODIFY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MESSAGENOTIFICATION> MESSAGENOTIFICATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MESSAGENOTIFICATION> MESSAGENOTIFICATIONs1 { get; set; }
    }
}
