//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKPLAN2TASKFELTILIZER
    {
        public int OBJECTID { get; set; }
        public Nullable<int> WOKRPLAN2TASKID { get; set; }
        public Nullable<int> FELTILIZERID { get; set; }
        public Nullable<decimal> WATERCOUNT { get; set; }
        public Nullable<decimal> FELTILIZERCOUNT { get; set; }
    
        public virtual FERTILIZER FERTILIZER { get; set; }
        public virtual WORKPLAN2TASKS WORKPLAN2TASKS { get; set; }
    }
}
