//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKPLAN2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WORKPLAN2()
        {
            this.WORKPLAN2PARCELS = new HashSet<WORKPLAN2PARCELS>();
            this.WORKPLAN2TASKS = new HashSet<WORKPLAN2TASKS>();
        }
    
        public int OBJECTID { get; set; }
        public Nullable<int> WORKS_ID { get; set; }
        public Nullable<int> RESPONDERID { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<System.DateTime> FINISDATE { get; set; }
        public Nullable<bool> ISDONE { get; set; }
        public Nullable<int> CREATORID { get; set; }
    
        public virtual Worker Worker { get; set; }
        public virtual Worker Worker1 { get; set; }
        public virtual WORK WORK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORKPLAN2PARCELS> WORKPLAN2PARCELS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORKPLAN2TASKS> WORKPLAN2TASKS { get; set; }
    }
}
