//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORK_PLAN_MODIFY
    {
        public int OBJECTID { get; set; }
        public Nullable<int> STATUS_ID { get; set; }
        public Nullable<int> WORK_PLAN_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    
        public virtual STATUSMODIFY STATUSMODIFY { get; set; }
        public virtual User User { get; set; }
        public virtual WORK_PLAN WORK_PLAN { get; set; }
    }
}
