//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.PARCELs = new HashSet<PARCEL>();
            this.Users = new HashSet<User>();
            this.WORK_PLAN = new HashSet<WORK_PLAN>();
            this.WORK_PLAN_TECHNIQUE = new HashSet<WORK_PLAN_TECHNIQUE>();
            this.WORK_PLAN_WORKERS = new HashSet<WORK_PLAN_WORKERS>();
            this.STOCKMODIFies = new HashSet<STOCKMODIFY>();
            this.DOCMESSAGEs = new HashSet<DOCMESSAGE>();
            this.DOCMESSAGEs1 = new HashSet<DOCMESSAGE>();
            this.DOCUMENTS = new HashSet<DOCUMENT>();
            this.WOKRPLAN2TASKQUEUETECHNICAL = new HashSet<WOKRPLAN2TASKQUEUETECHNICAL>();
            this.WORKPLAN2 = new HashSet<WORKPLAN2>();
            this.WORKPLAN21 = new HashSet<WORKPLAN2>();
            this.WORKPLAN2QUEUEWORKERS = new HashSet<WORKPLAN2QUEUEWORKERS>();
        }
    
        public int ID { get; set; }
        public int Professions_id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Fathername { get; set; }
        public int Gerder_id { get; set; }
        public string Email { get; set; }
        public bool Status { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public System.DateTime Create_data { get; set; }
        public string Phone { get; set; }
        public string Fin_number { get; set; }
        public string Serial_number { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<int> TurniketID { get; set; }
    
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARCEL> PARCELs { get; set; }
        public virtual Profession Profession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORK_PLAN> WORK_PLAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORK_PLAN_TECHNIQUE> WORK_PLAN_TECHNIQUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORK_PLAN_WORKERS> WORK_PLAN_WORKERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCKMODIFY> STOCKMODIFies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCMESSAGE> DOCMESSAGEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCMESSAGE> DOCMESSAGEs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENT> DOCUMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WOKRPLAN2TASKQUEUETECHNICAL> WOKRPLAN2TASKQUEUETECHNICAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORKPLAN2> WORKPLAN2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORKPLAN2> WORKPLAN21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORKPLAN2QUEUEWORKERS> WORKPLAN2QUEUEWORKERS { get; set; }
    }
}
