//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORK_PLAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WORK_PLAN()
        {
            this.DAYLY_WORK_PLAN = new HashSet<DAYLY_WORK_PLAN>();
            this.WORK_PLAN_MODIFY = new HashSet<WORK_PLAN_MODIFY>();
            this.MESSAGENOTIFICATIONs = new HashSet<MESSAGENOTIFICATION>();
        }
    
        public int OBJECTID { get; set; }
        public Nullable<int> WORKS_ID { get; set; }
        public Nullable<int> RESPONDER_ID { get; set; }
        public Nullable<int> PARCEL_ID { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> FINISH_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAYLY_WORK_PLAN> DAYLY_WORK_PLAN { get; set; }
        public virtual PARCEL PARCEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORK_PLAN_MODIFY> WORK_PLAN_MODIFY { get; set; }
        public virtual Worker Worker { get; set; }
        public virtual WORK WORK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MESSAGENOTIFICATION> MESSAGENOTIFICATIONs { get; set; }
    }
}
