//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKPLAN2QUEUEWORKERS
    {
        public int OBJECTID { get; set; }
        public Nullable<int> WORKPLAN2TASKQUEUEID { get; set; }
        public Nullable<int> WORKERID { get; set; }
    
        public virtual Worker Worker { get; set; }
        public virtual WORKPLAN2TASKQUEUE WORKPLAN2TASKQUEUE { get; set; }
    }
}
