//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORK_PLAN_WORKERS
    {
        public int OBJECTID { get; set; }
        public Nullable<int> DAYLY_WORK_PLAN_ID { get; set; }
        public Nullable<int> WORKER_ID { get; set; }
    
        public virtual QueuePlan QueuePlan { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
