//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UluagroAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKPLAN2TASKQUEUE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WORKPLAN2TASKQUEUE()
        {
            this.WOKRPLAN2TASKQUEUETECHNICAL = new HashSet<WOKRPLAN2TASKQUEUETECHNICAL>();
            this.WORKPLAN2QUEUEWORKERS = new HashSet<WORKPLAN2QUEUEWORKERS>();
        }
    
        public int OBJECTID { get; set; }
        public Nullable<System.TimeSpan> STARTHOURS { get; set; }
        public Nullable<System.TimeSpan> ENDHOURS { get; set; }
        public string NOTE { get; set; }
        public Nullable<int> WORKPLAN2TASKID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WOKRPLAN2TASKQUEUETECHNICAL> WOKRPLAN2TASKQUEUETECHNICAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORKPLAN2QUEUEWORKERS> WORKPLAN2QUEUEWORKERS { get; set; }
        public virtual WORKPLAN2TASKS WORKPLAN2TASKS { get; set; }
    }
}
